version: "3.8"
services:
  grafana:
    image: grafana/grafana
    volumes:
      - ./data:/var/lib/grafana
  gw:
    build:
      dockerfile: Dockerfile.gw
      context: .
    command: ["gw", "--url", "http://grafana:3000", "--secrets", "/run/secrets/tunnel.json"]
    secrets:
      - tunnel.json
secrets:
  tunnel.json:
    file: secrets/tunnel.json
